# Generated by Django 2.2.6 on 2022-08-14 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urlshortner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(blank=True, max_length=900)),
                ('new_url', models.CharField(blank=True, max_length=80)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
